environment:
  DOCKER_USER_NAME: ENCRYPTED[b75ee3bd0bd835d7d74d2598b54fee3d0b743919a48c87829bf99fab6dd9a296cce88bfa81dd9d660d7c3acbb6e589ce]
  DOCKER_PASSWORD: ENCRYPTED[dcb999313b7216ea7fb1181de5fdac8cdba6ea0d8fdca287f2cc1713c110dbaa9fceafb5ffe0fe8dfde7bbc520abdfae]

docker_builder:
  name: Linux
  only_if: $CIRRUS_BRANCH != $CIRRUS_DEFAULT_BRANCH
  setup_script:
    - docker --version
  build_tools_script: docker buildx build --load --tag cirrusci/android-sdk:tools sdk/tools
  build_sdk_script: docker buildx build --load --tag cirrusci/android-sdk:33 sdk/33
  build_ndk_script: docker buildx build --load --tag cirrusci/android-sdk:33-ndk sdk/33-ndk

docker_builder:
  name: Linux
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH
  setup_script:
    - docker --version
  login_script: docker login --username $DOCKER_USER_NAME --password $DOCKER_PASSWORD
  build_tools_script: docker buildx build --push --cache-from cirrusci/android-sdk:tools --tag cirrusci/android-sdk:tools sdk/tools
  build_sdk_script: docker buildx build --push --cache-from cirrusci/android-sdk:33 --tag cirrusci/android-sdk:33 sdk/33
  build_ndk_script: docker buildx build --push --cache-from cirrusci/android-sdk:33-ndk --tag cirrusci/android-sdk:33-ndk sdk/33-ndk
