environment:
  DOCKER_USER_NAME: ENCRYPTED[b75ee3bd0bd835d7d74d2598b54fee3d0b743919a48c87829bf99fab6dd9a296cce88bfa81dd9d660d7c3acbb6e589ce]
  DOCKER_PASSWORD: ENCRYPTED[dcb999313b7216ea7fb1181de5fdac8cdba6ea0d8fdca287f2cc1713c110dbaa9fceafb5ffe0fe8dfde7bbc520abdfae]

docker_builder:
  name: Linux
  build_tools_script: docker build --cache-from cirrusci/android-sdk:tools --tag cirrusci/android-sdk:tools sdk/tools
  build_next_sdk_script: docker build --cache-from cirrusci/android-sdk:30 --tag cirrusci/android-sdk:30 sdk/30
  push_script: ./scripts/push_docker.sh

docker_builder:
  skip: "!changesInclude('**/*windows*/**')"
  name: Windows
  platform: windows
  os_version: 2019
  build_tools_script: docker build --cache-from cirrusci/android-sdk:tools-windowsservercore-2019 --tag cirrusci/android-sdk:tools-windowsservercore-2019 sdk\tools-windowsservercore-2019
  build_sdk_script: docker build --cache-from cirrusci/android-sdk:30-windowsservercore-2019 --tag cirrusci/android-sdk:30-windowsservercore-2019 sdk\30-windowsservercore-2019
  push_script: ./scripts/push_docker.bat
