docker_builder:
  name: Build
  only_if: $CIRRUS_BRANCH != $CIRRUS_DEFAULT_BRANCH
  version_script: docker --version
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_tools_script: |
    docker buildx build --platform linux/amd64,linux/arm64 \
      --tag ghcr.io/cirruslabs/android-sdk:tools \
      sdk/tools
  build_sdk_script: |
    docker buildx build --platform linux/amd64,linux/arm64 \
      --tag ghcr.io/cirruslabs/android-sdk:34 \
      sdk/34
  build_ndk_script: |
    docker buildx build --platform linux/amd64,linux/arm64 \
      --tag ghcr.io/cirruslabs/android-sdk:34-ndk \
      sdk/34-ndk

docker_builder:
  name: Push
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH
  env:
    GITHUB_TOKEN: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
  version_script: docker --version
  login_script:
    - echo $GITHUB_TOKEN | docker login ghcr.io -u fkorotkov --password-stdin
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_tools_script: |
    docker buildx build --platform linux/amd64,linux/arm64 --push \
      --tag ghcr.io/cirruslabs/android-sdk:tools \
      sdk/tools
  build_sdk_script: |
    docker buildx build --platform linux/amd64,linux/arm64 --push \
      --tag ghcr.io/cirruslabs/android-sdk:34 \
      sdk/34
  build_ndk_script: |
    docker buildx build --platform linux/amd64,linux/arm64 --push \
      --tag ghcr.io/cirruslabs/android-sdk:34-ndk \
      sdk/34-ndk
